name: Swift

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, OS=14.0, name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
        
      - name: Build
        run: |
          xcodebuild clean build -project Example/Example.xcodeproj -scheme Example -destination "${destination}" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
