name: Build and Test

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build:
    runs-on: macos-12
  
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
        
      - name: Force Xcode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
        
        
      - name: Build Setup
        run: >-    
          xcodebuild test
          -project Example/Example.xcodeproj
          -scheme Example
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
